//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "liquidity")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ts: i64,
    pub target_token_liquidity: i64,
    pub sol_liquidity: i64,
    pub pool_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pool::Entity",
        from = "Column::PoolId",
        to = "super::pool::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Pool,
}

impl Related<super::pool::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pool.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
