//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pool")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub target_token_mint: String,
    pub target_token_pool_vault: String,
    pub sol_pool_vault: String,
    pub rugged: bool,
    pub done_indexing: bool,
    pub started_indexing_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::liquidity::Entity")]
    Liquidity,
}

impl Related<super::liquidity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Liquidity.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
